### ISSUE TITLE
TNT数据集测试的depth_interval设置

### ISSUE THREAD

**Issue by xiehao-ai** [YueyueBird-su/DFPN_Module_in_MVS#2]
感谢作者的开源代码！
最近刚开始学习MVS方向的内容，在使用作者代码测试TNT数据集时，看到加载数据的代码，depth_interval使用的是指定的数值（例如Horse: 1.5e-3），而不是从cam.txt中读取的depth_interval，想问一下这样设置的原因是什么？
另外想问一下，tnt数据集中初始给出的内参和short_range_cameras_for_mvsnet给出的内参区别是什么？
谢谢

**Comment by YueyueBird-su** [comment]
！感谢你对这项工作的关注
我想 [yaoyao](https://github.com/YoYo000/MVSNet/issues/14) 在MVSNet中的回答能解决你的这两个问题。
总的来说，这两个 trick 都是针对 tnt 数据集**室外场景导致的深度范围过大**，而**深度采样数量受显存限制**这一问题。
所以需要人为的调整深度范围和采样间隔。

不知道这样回答是否能解决你的困惑。
可以的话，把两种方式实现了对比一下看看结果。

**Comment by xiehao-ai** [comment]
感谢您的回复！
我看了您给的链接，有一些疑惑想请教一下。我理解原始给出的相机参数中深度范围较大，深度采样的数量多，显存不足以支撑；新的相机参数表示的深度范围小。我想，增大深度采样的间隔depth_interval，这时同样的深度范围，所需深度采样的数量numdepth就变小了，但没看到有人这样做。直接减小采样间隔，那么最终得到的深度范围还可以覆盖到待测的目标吗？这里有些疑惑。
我算了一下，按照源码中给出的参数，例如horse，depth_interval为1.5e-3，depth_min为0.14706，num_depth为192，这样算出来depth_max为0.435，这可以理解为待预测目标的深度处于0.14706米到0.435米之间吗？但从图片中来看，马的深度范围要比这个区间广，我用源码中的设置跑出来的点云，在cloudcompare中量了一下，
![7E60A787-7521-4fc1-B7FB-F004ED5A1ED6](https://github.com/YueyueBird-su/DFPN_Module_in_MVS/assets/44167522/f5c26e8f-f0b1-4d07-a2bd-f3883dbacb82)
箱子的长度为0.24米，感觉尺度上有点问题，从图片中看箱子应该很长，单位应该是米级的（这里还有个疑问，DTU数据集中深度是以mm为单位给出的，tnt和blendedmvs数据集中的深度单位是m，网络输出结果的单位是和输入数据的单位保持一致吗，测试DTU数据集时网络输出深度的单位是mm，测试tnt和blendedmvs数据集时网络输出深度的单位是m，可以这么理解吗？）。
最近刚开始学习MVS的内容，有些内容理解的不是特别清楚，期待得到您的回复，谢谢！

**Comment by YueyueBird-su** [comment]
> 我理解原始给出的相机参数中深度范围较大，深度采样的数量多，显存不足以支撑；新的相机参数表示的深度范围小。我想，增大深度采样的间隔depth_interval，这时同样的深度范围，所需深度采样的数量numdepth就变小了，但没看到有人这样做。

首先，你得知道你重建的目标是什么，是包含所有场景还是目标物体精度更好，如果按照取最大概率的深度作为像素点深度，增大深度采样间隔反而会导致准确度降低。

> 我算了一下，按照源码中给出的参数，例如horse，depth_interval为1.5e-3，depth_min为0.14706，num_depth为192，这样算出来depth_max为0.435，这可以理解为待预测目标的深度处于0.14706米到0.435米之间吗？

这块得看看这个数据集的相机参数是怎么恢复的了，如果是通过SFM恢复了相机位姿，但是没有恢复尺度的话，单位应该是mm。

> 网络输出结果的单位是和输入数据的单位保持一致吗

这块不影响的，网络中深度采样是设定的【最小，最大】采样的，不会因为采样了深度的单位就变了。

希望这能解答你的疑惑~

**Comment by xiehao-ai** [comment]
非常感谢！
